### ISSUE TITLE
standard deviation includes not permuted correlation

### ISSUE THREAD

**Issue by ntraut** [jwcarr/mantel#10]
when we ask for 100 permutations, the first entry of the correlations array is the direct correlation, and the 99 others are the permuted ones. the standard deviation computation doesn't exclude the direct correlation, which should be the case (ideally there should be really 100 permutations and the standard deviation should be only on those).

**Comment by jwcarr** [comment]
Hi! Thanks for raising this issue.

Do you have a statistical explanation for why the veridical correlation should be excluded? It's been a long time since I coded this, but I seem to recall that there was a specific reason why I coded it this way.

Like, imagine you only have four objects, such that the number of possible permutations is 4! = 24. In such a small case, you don't need random permutations, you can just run all 24 permutations and compare them against the veridical. To compute the empirical p-value, you would ask, how many of the correlations are greater than or equal to the veridical, *including the veridical itself*? Thus, if the veridical correlation was stronger than all others, you'd get a p-value of 1/24. But if you did not include the veridical, then it would be possible for the p-value to be zero.

If we transfer this logic to the random permutations case, then it seems to make sense that at least one of the permutations must be greater than or equal to the veridical – i.e. because we know that at least one permutation (the observed permutation) is equal to the veridical.

I think this gives a justification for why the veridical should be included when computing the p-value. Now your point relates to the mean and std, but it feels to me like the same logic applies. Imagine again the deterministic case with 24 possible permutations. If you ask for the mean – the expected correlation over possible permutations – then you would want all 24 permutations to be included; you wouldn't want the mean of just the 23 other possible permutations that weren't observed.

Does that make sense?

**Comment by ntraut** [comment]
For me the goal of computing this standard deviation is to get an insight on the null distribution. To the question "Is it harmful to include the veridical correlation when performing only a subset of permutations?", the answer is certainly yes, as we are including a value which is outside of the null hypothesis.

To the question "Is it harmful to include the veridical correlation when performing all possible permutations?", the answer is less certain, but the impact of this decision should be minimal for a large enough sample size.

For simplicity, I would not include the veridical correlation in both cases, but it may also be possible to not include it only when a subset of all permutations are evaluated.

**Comment by jwcarr** [comment]
> we are including a value which is outside of the null hypothesis

To me, the null distribution theoretically includes all outcomes that could happen by chance, which includes the observed outcome itself. But I think I understand your point: you're saying that, by including the veridical in the *sample* from the null, the sample distribution is biased towards the veridical. I'm not really sure what the right answer is, but consider the following:

1. This bias could be seen as a positive thing, since it gives representation to permutations that are known to exist, but which might be very rare and unlikely to be randomly generated with *insufficient* sample sizes.
2. The bias is conservative with respect to the hypothesis, since it artificially moves the null towards the veridical and therefore makes it harder to reject the null.
3. The bias is probably so insignificant that it's no worse than rounding error, assuming you have e.g. 10,000+ sims.

But I do agree that the current design is a bit weird, since people will expect all sample correlations to be derived from random permutations.

The solution you suggest in your PR has the benefit of being simple, but it's a bit problematic since, if the user asks for 100 sims, they should get 100 correlations, not 99. This has the potential to break people's code if, for some reason, it relies on there being 100 correlations. So, I think it would be preferable that we generate 100 correlations.

But looking over the code, I can see that making this change is not so straight-forward. Currently, `MantelResult` does not know whether the correlations were generated in the stochastic way or the deterministic way, and I think this affects whether or not the veridical should be included in the mean and std. (Another issue that occurs to me now, is that we probably should be making a distinction between the population and sample standard deviations – NumPy uses the population std by default, it seems).

I can see a few different options for fixing this, but I don't think it's possible without passing some flag into `MantelResult` so that that the mean, std, and p-value computations can be handled differently. What do you think?

**Comment by jwcarr** [comment]
I think this makes sense, but let me know what you think:

### Stochastic tests
- N random permutations should be performed
- The mean should be computed on all N
- The std should be computed on all N with `ddof=1`
- To prevent a p-value of 0, the p-value could be computed in two possible ways
  1. With the veridical included (so N+1 correlations total)
  2. Only on the N random correlations but a `+1` would be added to the numerator and denominator

### Deterministic tests
- All M possible permutations should be performed
- The mean should be computed on all M
- The std should be computed on all M with `ddof=0`
- The p-value should be computed on all M

**Comment by ntraut** [comment]
For me it's ok to have the veridical correlation included in the N permutations as it is needed to compute the p-value, but just not include it in the computation of the standard deviation to avoid the bias.

This bias is problematic even if it's conservative as it is dependent of the number of permutations performed. When the sample size is large we may want to do only a limited number of permutations, and we don't want this choice to impact the result other than by a lack of precision.

I would also exclude the veridical correlation when performing the standard deviation of all the permutations as it does not have a special meaning in the null hypothesis so it should not be harmful, and always use `ddof=1` to avoid underestimation of the standard deviation.

**Comment by jwcarr** [comment]
I agree that it's not ideal to artificially include the veridical among the randomly sampled permutations when computing the mean and STD. However, when performing the test with all possible permutations, I do believe the observed permutation should be included, since it is part of the null-distribution (i.e., the set of all possible outcomes that could happen by chance). Therefore, the mean and STD need to be computed differently depending on whether a stochastic or deterministic test was conducted. I have pushed a commit to address this (6570827) and an additional commit to use the sample STD in the case of stochastic tests (1f92c4c).

Let me know if you still think this is a problem, but if not, I will push this in a new release later this week.

**Comment by jwcarr** [comment]
I've now pushed these changes in v2.2.2

**Comment by ntraut** [comment]
I would have preferred my simpler solution but I'm ok with your solution. One disadvantage is that for example if we ask for 10 permutations and the random permutations are all weaker, we get a p-value of `0.09090909090909091` which can be confusing as we may expect something like `0.1`. I still don't see why removing the veridical correlation when computing the standard deviation of all permutations would be a big issue as for me they still just represent a subset of the null hypothesis which is a continuous thing we don't have directly access but we try to approach it by doing those permutations.

**Comment by jwcarr** [comment]
I think there are a few separate (but interconnected) issues here. First let me address your solution, and then I'll come back to the p-value thing.

**Your solution**

Although your solution was nice and simple, requiring only a minimal change to the codebase, I think it was problematic for two reasons.

1. If the user requests 1000 permutations, then 1000 random permutations should be performed and the calculated mean and std should be based on 1000 permutations. The old codebase was suboptimal because – unbeknown to the user – it only performed 999 permutations and then artificially appended the veridical to make it up to 1000. This was essentially a hack to address the p-value issue (see below), but – as you rightly pointed out – it wasn't really appropriate for computing the mean and std, which should have been based on 1000 genuinely random permutations. So I felt that your solution was kind of a hack on top of a hack and that it was better to tackle the root problem.

2. More importantly, your solution did not account for the fact that, in the special case of "deterministic tests", the veridical should be included. Not as an artificially appended extra thing, but as a complete description of the null-distribution. In this kind of test the aim is to compare the observed correlation against the correlations that could have occurred under all possible permutations of the objects. This includes the observed arrangement itself. The null-hypothesis states something like: there is nothing special about the observed arrangement; any other arrangement is just a likely; all arrangements are equally possible. Thus, the null-distribution consists of all permutations. A stochastic test samples from this permutation space, while a deterministic test considers all of them. If we were to artificially exclude the observed permutation (or any of the permutations – it just so happened that permutation 0 was always the observed arrangement given the way the code works), then the mean would not be an accurate reflection of what would be expected to happen by chance.

So I hope this explains why I felt a more radical change to the code was required.

But let me try to answer your question another way. Imagine we have a small number of objects (e.g. 4), so it is feasible to perform a deterministic test because there are only 4! = 24 permutations. If we were, instead, to run a stochastic test with 1000 permutations, then each of the 24 possible arrangements is equally likely to be generated and each would be represented approximately an equal number of times (1000 / 24 = 41.6667 times each). However, this stochastic test would (a) be wasteful and (b) would not give a consistent/precise result because of the random sampling. The deterministic test computes only the 24 possible outcomes and gives an exact result. As you can see, if we artificially exclude 1 of the 24 possible outcomes, the result would be wrong (not merely a poor estimate) and the result would disagree with the approximation calculated by a stochastic test (which *would* be based on all 24 possibilities). Importantly, the result could be skewed quite dramatically in cases like this because we are excluding one outcome from a fairly small set of possible outcomes.

**P-value calculation**

In the example you give where you perform ten permutations and all ten are weaker than the veridical, then the calculated p-value would be 0. This is because the empirical p-value is the proportion of permutations >= the veridical. If all are weaker, then you get 0/10 = 0. This issue never occurs in the case of deterministic tests because the veridical is always present in the permutations, so there is always at least 1 permutation >= to the veridical. But, in the case of stochastic tests, we have a problem: since we are sampling from the permutation space, there's a reasonably good chance that we will never sample any permutations >= the veridical, resulting in a p-value of 0. Of course, we know that the p-value cannot truly be zero because we know that there's at least one possible permutation >= the veridical (i.e. the veridical itself).

The standard way to address this issue in permutation testing is to put +1's in the numerator and denominator of the p-value calculation. In your example, this gives us 1/11 = 0.09090909. Essentially, we just pretend that the observed correlation happened to occur among the permutations to prevent a p-value of 0 from occurring. An alternate option (which is what the code does) is to artificially append the veridical to the list of random correlations, which has the same effect. The original codebase only performed 9 random permutations and then added in the veridical to give 1/10 = 0.1. So, I guess you're right, that the result looks cleaner in this artificial scenario, but it's still based on a hack to avoid a p-value of 0. The alternative option would be to only generate n-1 random permutations but, as I said above, this goes against what the user requested, so `len(result.correlations) == 9` despite the user asking for 10.

Hope this explains everything!
