### ISSUE TITLE
Include mantel test with nan entries

### ISSUE THREAD

**Issue by juergspaak** [jwcarr/mantel#6]
Hi, your code seems great and I would really like to run it, however, I do have some np.nan in my datasets. From what I understand the code would run just fine if all the .sum() and .mean() were replaced with .nansum() and .nanmean()
Is that possible?

**Comment by jwcarr** [comment]
Hi! In principle, I would be open to doing something like this, but there are a few things I'm not sure about...

1. Under what circumstances would one have a distance of NaN? I mean, off the top of my head, I can't think of any obvious reasons why the distance between two objects would be NaN.
2. Does it make sense to compute a correlation when there are NaNs. scipy.stats.pearsonr, for example, explicitly raises an error if the data contains NaNs.
3. I wonder if a better/safer solution is to strip out the NaNs before passing into the test because then the user has to explicitly think about the fact that their data contains NaNs.

**Comment by juergspaak** [comment]
thanks

1. We measure the distance of resource consumption of species (called niche difference) in experiments. Some of the experiments failed/field observations do not have the necessary data.
2. I think the pearsonr just raises an error because of convenience, there's nothing theoretically wrong with having nan. Of course in the pearson this is equivalent to ignoring them.
3. However, ignoring them in the mantel is problematic. I have an 18 by 18 matrix with some nan entries. Not entire nan rows. But omiting all rows with a nan would reduce my matrix to a 3 by 3, So that wouldn't be really cool.

**Comment by jwcarr** [comment]
Ah, I see, so you have missing values rather than NaNs specifically. I somehow never realized that Numpy doesn't actually have an NA type (I guess I've been lucky enough to never have to deal with missing data).

So yeah, I see your problem. In order to maintain the current behavior, I think the best thing to do is add an extra `ignore_nans` option, which is off by default. Can you check if this commit works for you / makes sense? If so, I'll release a new version to PyPI.

**Comment by juergspaak** [comment]
the spatial.distance.is_valid_dm(X) test throws an error, presumably because it tests X.T == X, which is wrong for every np.nan entry.
When I commented that out it worked fine, thank you very much.

Additionally, I got p = 0.0001 as a result, which is the minimal for perms = 10000. You could consider adding a message for that case indicating that p can't be lower with chosen settings and is likely to be even lower.

**Comment by jwcarr** [comment]
How confident are you about the `nansum` approach? Something feels a bit fishy to me:

```python
from numpy import nan, corrcoef
import mantel

dists1 = [0.2, 0.4, 0.3, 0.6, 0.9, 0.4]
dists2 = [0.3, 0.3, 0.2, 0.7, nan, 0.3]
print(mantel.test(dists1, dists2, ignore_nans=True))

dists1 = [0.2, 0.4, 0.3, 0.6, nan, 0.4]
dists2 = [0.3, 0.3, 0.2, 0.7, 0.8, 0.3]
print(mantel.test(dists2, dists1, ignore_nans=True)) # dists2 passed in as X

print(corrcoef([0.2, 0.4, 0.3, 0.6, 0.4], [0.3, 0.3, 0.2, 0.7, 0.3]))
```

gives this output:

```python
(0.439892076757162, 0.3333333333333333, 0.9805793115936009)
(0.5781314528627276, 0.3333333333333333, 1.2236168384926989)
[[1.         0.83005736]
 [0.83005736 1.        ]]
```

I believe the veridical correlation should be the same in both cases because essentially we can think of this as just ignoring the 5th pair (i.e. where 0.9 is paired with 0.8). So I would expect the veridical correlation to be 0.83005736.

I have an alternative idea about how to do this: https://github.com/jwcarr/mantel/commit/e89fa87ff642fe1724f1f7ba6b064b1f66f1a09e This gives more sensible results (I think):

```python
(0.8300573566392896, 0.3333333333333333, 0.9805793115936009)
(0.8300573566392896, 0.3333333333333333, 1.2236168384926989)
[[1.         0.83005736]
 [0.83005736 1.        ]]
```

But the limitation is that only one of the matrices can contain NaNs (but maybe it's possible to overcome this limitation).

**Comment by juergspaak** [comment]
so, I didn't fully understand the idea of your fix.. What is the reasoning, could you explain this in words?
I do however agree that the two datasets should give the same result. Additionally, we should get the same result if we replace both entries by np.nan, which is not the case either... In any case, I think the version where both entries (in X and Y) are replaced by np.nan should yield the correct answer. So maybe change x and y internally to have identical np.nan entries? I had the impression that your code does something like that, right?

To test which is the correct I ran the following code:

`import numpy as np
from mantel import test
itera = 1000
p = np.empty((4,itera))
for i in range(itera):
    print(i)
    a, b = np.random.uniform(0,1,(2, 10,10))
    a = a+a.T
    b = b+b.T
    np.fill_diagonal(a,0)
    np.fill_diagonal(b,0)
    a_ = a.copy()
    b_ = b.copy()
    
    a_[[0,1],[1,0]] = np.nan
    b_[[0,1],[1,0]] = np.nan
    
    p[0,i] = test(a,b, perms = 1000, ignore_nans=True)[1]
    p[1,i] = test(a_,b, perms = 1000, ignore_nans=True)[1]
    p[2,i] = test(a,b_, perms = 1000, ignore_nans=True)[1]
    p[3,i] = test(a_,b_, perms = 1000, ignore_nans=True)[1]

print(np.sum(p<0.05, axis = 1))
`

I.e. I perform the mantel test to 1000 random matrices and record the p values. The print at the end states how often this is significant, which should be 50 times, but I always got around 40 times (independent of which method). So I started to wonder whether something else is off or I misunderstand how this is supposed to work.

**Comment by jwcarr** [comment]
So we agree that all three of these cases should have the same raw correlation:

```python
X = [0.2, 0.4, 0.3, 0.6, nan, 0.4]
Y = [0.3, 0.3, 0.2, 0.7, 0.8, 0.3]

X = [0.2, 0.4, 0.3, 0.6, 0.9, 0.4]
Y = [0.3, 0.3, 0.2, 0.7, nan, 0.3]

X = [0.2, 0.4, 0.3, 0.6, nan, 0.4]
Y = [0.3, 0.3, 0.2, 0.7, nan, 0.3]
```

In other words, all three should be equivalent to:

```python
X = [0.2, 0.4, 0.3, 0.6, 0.4]
Y = [0.3, 0.3, 0.2, 0.7, 0.3]
```

However, a problem arises if there is a nan in both arrays, like the third case above. When this happens, a permutation of Y could look like this:

```python
X = [0.2, 0.4, 0.3, 0.6, nan, 0.4]
Y = [0.3, 0.7, nan, 0.2, 0.3, 0.3] # permuted Y
```

Now, when we perform the correlation, we have to eliminate two sets of values, which is equivalent to this:

```python
X = [0.2, 0.4, 0.6, 0.4]
Y = [0.3, 0.7, 0.2, 0.3]
```

So this means that sometimes the correlation will be on four pairs of values and sometimes on five pairs of values, depending on how things are permuted (i.e. if the two nans line up, then you only have to throw away one pair of values). So, this makes me think that allowing nans in both arrays is going to be problematic. (do you need this for your particular use case?)

My suggested approach is particularly hard to understand in the code because of various optimizations, but basically this is my idea:

1. Only allow nans in Y
2. Get the finite values in Y and the corresponding values in X to do the raw correlation
3. Represent Y in matrix form
4. Run lots of permutations of the matrix:
  a. Convert the matrix permutation back into vector form
  b. Get the indices of the finite values in Y
  c. Grab the corresponding values in X and correlate again
5. Finally, compare the true correlation to the randomized ones

**Comment by jwcarr** [comment]
I realized there was another bug in my implementation, which is now fixed (https://github.com/jwcarr/mantel/commit/c5a21e85bd0182d75744ec44578e95bdaae0154c).

Thanks for the simulation code – this is a good sanity check. I modified it slightly so that only `b` contains a nan:

```python
import numpy as np
import mantel

n_sims = 1000
p = np.zeros((n_sims, 2))

for i in range(n_sims):
	print(i)

	a, b = np.random.uniform(0, 1, (2, 10, 10))
	a = a + a.T
	b = b + b.T
	np.fill_diagonal(a, 0)
	np.fill_diagonal(b, 0)
	
	b_with_nan = b.copy()
	b_with_nan[(0,1), (1,0)] = np.nan

	p[i, 0] = mantel.test(a, b, perms=1000, ignore_nans=True)[1]
	p[i, 1] = mantel.test(a, b_with_nan, perms=1000, ignore_nans=True)[1]

print(np.sum(p < 0.05, axis=0))
```

I did five runs, and the results look pretty sound to me:

```python
[52 52] # run 1
[39 40] # run 2
[51 48] # run 3
[46 51] # run 4
[47 47] # run 5
```

So I'm still not sure how to approach allowing nans in both matrices, or whether this is even possible. My hunch is that any solution I can come up with will be, at best, a bit hacky and ad hoc. Consider what happens in this case, for example:

```python
X = [nan, nan, nan, 0.6, 0.9, 0.4] # original X
Y = [nan, nan, nan, 0.7, 0.8, 0.3] # original Y
Y = [0.3, 0.7, 0.8, nan, nan, nan] # permutation of Y
```

**Comment by juergspaak** [comment]
So I had a look at what others did and I found a solution in R (another programing language) in the package vegan (a quite wildely distributed and reasonably well founded package). Their solution also seems to be wacky, their own documentation for dealing with nan is: 

na.rm	
Remove missing values in calculation of Mantel correlation. Use this option with care: Permutation tests can be biased, in particular if two matrices had missing values in matching positions.

So I'm not entirely sure what they do, but it's probably as wacky as your solution. Importantly, I tried out their solution to the two datasets you proposed (code at the end), but they don't yield the same results if we have NA in both datasets, but they do get different results than the approach used here.

All in all, not sure whether the mantel test is well behaved with NA. I do however need this for my actual research. To save us some trouble I think I'll just compute the mantel in R (TBH not entirely sure whether their method does the correct thing, but its the stuff used in my field, so if I make an error it's the same error as everybody does...).

thanks again for your help. I'm happy to close the issue.

PS: Code used in R for your reference

require(vegan)

X <- c(0.2, 0.4, 0.3, 0.6, NA, 0.4)
Y <- c(0.3, 0.3, 0.2, 0.7, 0.9, 0.3)

A <- matrix(NA, 4,4)
B <- matrix(NA, 4,4)

A[upper.tri(A)] = X
A[lower.tri(A)] = X
diag(A) = 0

B[upper.tri(B)] = Y
B[lower.tri(B)] = Y
diag(B) = 0
print(mantel(A,B, na.rm = TRUE))


If you change the 0.9 to NA it gets a different result, but changing NA to 0.8 and 0.9 to NA leads to the same result.

**Comment by jwcarr** [comment]
Good to know that others have wrestled with this issue. I had a look at their implementation (https://github.com/vegandevs/vegan/blob/master/R/mantel.R) and it seems to work in a similar way to mine, except they allow NAs in both matrices. My instinct tells me that Mantel should be well-behaved if only one matrix contains NAs. But as soon as you allow NAs in both matrices, there's lots of potential for problems. So, I think I will release the one-matrix-only version here in case it's useful to someone.

I fixed another slight problem (https://github.com/jwcarr/mantel/commit/9877742c52657b1ac052a8610c2cfc2291292c0e) and now I seem to (mostly) be getting the same results as the vegan package, e.g.:

```R
require(vegan)

X <- c(0.2, 0.4, 0.3, 0.6, 0.9, 0.4)
Y <- c(0.3, NA, 0.2, 0.7, NA, 0.3)

A <- matrix(NA, 4,4)
B <- matrix(NA, 4,4)

A[upper.tri(A)] = X
A[lower.tri(A)] = X
diag(A) = 0

B[upper.tri(B)] = Y
B[lower.tri(B)] = Y
diag(B) = 0

print(mantel(A,B, na.rm = TRUE)) 

Mantel statistic r: 0.8582 
      Significance: 0.25 
```

```python
from numpy import nan
import mantel


X = [0.2, 0.4, 0.3, 0.6, 0.9, 0.4]
Y = [0.3, nan, 0.2, 0.7, nan, 0.3]

print(mantel.test(X, Y, ignore_nans=True, tail='upper'))

(0.8582317538645401, 0.25, 1.010801493692354)
```

Ciao!
